workflows:
  react-native-android:
    name: React Native Android (Native Build)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_HOME: $HOME/Library/Android/sdk
        PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
    scripts:
      - name: Install Dependencies
        script: |
          # تثبيت المتطلبات الأساسية
          brew install node watchman
          
          # إنشاء مجلد Android SDK
          mkdir -p $ANDROID_HOME
          
          # تنزيل وتثبيت Android Command Line Tools
          cd $HOME
          curl -O https://dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip
          unzip commandlinetools-mac-11076708_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-mac-11076708_latest.zip
          
          # قبول التراخيص
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # تثبيت Android SDK و Build Tools
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"

      - name: Prepare Workspace
        script: |
          # تنظيف الملفات السابقة
          rm -rf android/build
          rm -rf android/app/build
          rm -rf node_modules
          mkdir -p android/app/src/main/assets
          
          # تثبيت dependencies
          npm install --legacy-peer-deps

      - name: Build APK
        script: |
          cd android
          ./gradlew clean assembleDebug
          
          # نسخ APK إلى المجلد الرئيسي
          APK_PATH=app/build/outputs/apk/debug/app-debug.apk
          if [ -f "$APK_PATH" ]; then
            cp $APK_PATH ../
          else
            echo "APK not found!"
            ls -la app/build/outputs/apk/debug/
            exit 1
          fi

      - name: Upload APK
        script: |
          if [ -f "app-debug.apk" ]; then
            echo "APK size: $(du -h app-debug.apk | cut -f1)"
            DOWNLOAD_URL=$(curl -X POST -T "app-debug.apk" "https://filebin.net/?filename=telon-app.apk" | grep -o 'https://filebin.net/[^"]*')
            echo "Download URL: $DOWNLOAD_URL"
          else
            echo "APK not found after build!"
            ls -la
            exit 1
          fi
    artifacts:
      - app-debug.apk
