workflows:
  react-native-android:
    name: React Native Android (Native Build)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_HOME: $HOME/Library/Android/sdk
        PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
    scripts:
      - name: Install Dependencies
        script: |
          brew install node watchman
          mkdir -p $ANDROID_HOME
          cd $HOME
          curl -O https://dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip
          unzip commandlinetools-mac-11076708_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-mac-11076708_latest.zip
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"

      - name: Prepare Workspace
        script: |
          # تحديد المسار الصحيح للمشروع الرئيسي
          PROJECT_PATH=$(find . -type d -name 'android' -path '*/node_modules/*' -prune -o -path '*/android' -print | grep -m 1 '/android$' | xargs dirname)
          if [ -z "$PROJECT_PATH" ]; then
            echo "Error: Android project directory not found!"
            find . -type d -name 'android'
            exit 1
          fi
          
          echo "Detected project path: $PROJECT_PATH"
          cd "$PROJECT_PATH"
          
          rm -rf android/build android/app/build node_modules
          mkdir -p android/app/src/main/assets
          npm install --legacy-peer-deps
          
          echo "Project structure after preparation:"
          ls -la
          echo "Android directory content:"
          ls -la android

      - name: Build APK
        script: |
          # تحديد المسار الصحيح للمشروع الرئيسي
          PROJECT_PATH=$(find . -type d -name 'android' -path '*/node_modules/*' -prune -o -path '*/android' -print | grep -m 1 '/android$' | xargs dirname)
          cd "$PROJECT_PATH"
          
          if [ -f "android/gradlew" ]; then
            echo "Building from android directory"
            cd android
            chmod +x gradlew
            ./gradlew clean assembleDebug
            APK_PATH=app/build/outputs/apk/debug/app-debug.apk
          elif [ -f "gradlew" ]; then
            echo "Building from root directory"
            chmod +x gradlew
            ./gradlew clean assembleDebug -p android
            APK_PATH=android/app/build/outputs/apk/debug/app-debug.apk
          else
            echo "Error: gradlew not found in project!"
            find . -name gradlew
            exit 1
          fi
          
          # نسخ APK إلى المجلد الرئيسي للعملية
          if [ -f "$APK_PATH" ]; then
            cp "$APK_PATH" ../../app-debug.apk
          else
            echo "APK not found at: $APK_PATH"
            find "$(pwd)" -name '*.apk'
            exit 1
          fi

      - name: Upload APK
        script: |
          if [ -f "app-debug.apk" ]; then
            echo "APK size: $(du -h app-debug.apk | cut -f1)"
            DOWNLOAD_URL=$(curl -X POST -T "app-debug.apk" "https://filebin.net/?filename=telon-app.apk" | grep -o 'https://filebin.net/[^"]*')
            echo "Download URL: $DOWNLOAD_URL"
          else
            echo "APK not found after build!"
            echo "Current directory content:"
            ls -la
            echo "Searching for APK:"
            find . -name '*.apk'
            exit 1
          fi
    artifacts:
      - app-debug.apk
